services:
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  db:
    image: "postgres:16.3"
    hostname: $POSTGRES_HOST # NOTE: This is required to connect to the container from an app running on host.
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      # NOTE: mount local folder
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data