services:
  web:
    build: .
    ports:
      - 5000:5000

  db:
    image: "postgres:16.3"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password